name: gradient_borders
description: Gradient borders for inputs and containers. Borders package integrated with a basic flutter widgets as a container and input decorations. Easy in use, platform independent.
version: 1.0.1
repository: https://github.com/obiwanzenobi/gradient-borders

environment:
  sdk: ^3.9.0
  flutter: ^3.35.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
